<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ReportsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('reports')->insert([
            [
                'code' => 'AD001',
                'category_event' => 'agama',
                'content' => 'Saya mengeluhkan suara azan dari masjid yang terlalu keras setiap pagi dan malam, mengganggu tidur warga sekitar.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Melati No. 5, Sungai Keruh, 37571, Tebo Tengah, Tebo, Jambi, Indonesia',
                'created_at' => Carbon::now()->subDays(5),
                'updated_at' => Carbon::now()->subDays(3),
            ],
            [
                'code' => 'AD002',
                'category_event' => 'kesehatan',
                'content' => 'Pelayanan di Puskesmas sangat lambat dan beberapa obat tidak tersedia, padahal saya harus segera mendapatkan perawatan.',
                'media' => NULL,
                'status' => 'sudah_diverifikasi',
                'address' => 'Jl. Sehat No. 12, Sabuh, 73814, Teweh Baru, Kabupaten Barito Utara, Kalimantan Tengah, Indonesia',
                'created_at' => Carbon::now()->subWeeks(2),
                'updated_at' => Carbon::now()->subWeek(),
            ],
            [
                'code' => 'AD003',
                'category_event' => 'ketertiban_umum',
                'content' => 'Setiap malam, kendaraan diparkir sembarangan di jalanan umum sehingga menghalangi akses ke rumah warga.',
                'media' => NULL,
                'status' => 'sudah_selesai',
                'address' => 'Jl. Kebersihan No. 8, Kertobanyon, 63171, Geger, Madiun, Jawa Timur, Indonesia',
                'created_at' => Carbon::now()->subMonths(1),
                'updated_at' => Carbon::now()->subWeeks(2),
            ],
            [
                'code' => 'AD004',
                'category_event' => 'pekerjaan_umum_dan_penataan_ruang',
                'content' => 'Jalan di depan kantor kami sudah rusak selama berbulan-bulan dan belum ada upaya perbaikan dari pihak terkait.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Pembangunan No. 15, Tanggung, 66272, Campur Darat, Tulungagung, Jawa Timur, Indonesia',
                'created_at' => Carbon::now()->subMonths(2),
                'updated_at' => Carbon::now()->subMonth(),
            ],
            [
                'code' => 'AD005',
                'category_event' => 'pemberantasan_penyalahgunaan',
                'content' => 'Saya sering melihat adanya aktivitas mencurigakan terkait narkoba di lingkungan RT 03, mohon untuk ditindaklanjuti.',
                'media' => NULL,
                'status' => 'sudah_selesai',
                'address' => 'Jl. Amanah No. 22, Wukirsari, 55782, Imogiri, Bantul, Daerah Istimewa Yogyakarta, Indonesia',
                'created_at' => Carbon::now()->subMonths(3),
                'updated_at' => Carbon::now()->subMonth(),
            ],
            [
                'code' => 'AD006',
                'category_event' => 'perhubungan',
                'content' => 'Jadwal bus kota sering tidak sesuai dengan waktu yang sudah ditetapkan, menyebabkan banyak penumpang terlantar.',
                'media' => NULL,
                'status' => 'ditolak',
                'address' => 'Jl. Transportasi No. 30, Karangjati, 50552, Bergas, Kota Semarang, Jawa Tengah, Indonesia',
                'created_at' => Carbon::now()->subMonths(4),
                'updated_at' => Carbon::now()->subWeeks(3),
            ],
            [
                'code' => 'AD007',
                'category_event' => 'politik_dan_hukum',
                'content' => 'Ada kampanye politik yang dilakukan di sekolah, padahal tempat tersebut seharusnya netral dari kegiatan politik.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Demokrasi No. 40, Bumi Jawa, 34372, Batanghari Nuban, Lampung Timur, Lampung, Indonesia',
                'created_at' => Carbon::now()->subMonths(5),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'code' => 'AD008',
                'category_event' => 'perlindungan_konsumen',
                'content' => 'Saya membeli produk makanan di toko yang ternyata sudah kadaluarsa dan masih dijual tanpa peringatan.',
                'media' => NULL,
                'status' => 'sudah_diverifikasi',
                'address' => 'Jl. Konsumen No. 50, Jayamanik, 42361, Cimarga, Lebak, Banten, Indonesia',
                'created_at' => Carbon::now()->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(3),
            ],
            [
                'code' => 'AD009',
                'category_event' => 'ketertiban_umum',
                'content' => 'Tempat hiburan di sekitar komplek sering mengadakan acara sampai larut malam, menyebabkan kebisingan yang tidak nyaman.',
                'media' => NULL,
                'status' => 'sudah_selesai',
                'address' => 'Jl. Ketertiban No. 60, Gunungsari, 46256, Sadananya, Ciamis, Jawa Barat, Indonesia',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(4),
            ],
            [
                'code' => 'AD010',
                'category_event' => 'topik_lainnya',
                'content' => 'Pelayanan di kantor pemerintahan sangat lambat dan tidak ada kejelasan mengenai prosedur yang harus diikuti.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Pemerintahan No. 70, Kalinegoro, 56172, Mertoyudan, Kota Magelang, Jawa Tengah, Indonesia',
                'created_at' => Carbon::now()->subMonths(8),
                'updated_at' => Carbon::now()->subMonths(5),
            ],
            [
                'code' => 'AD011',
                'category_event' => 'agama',
                'content' => 'Pengelolaan masjid di kampung saya kurang terorganisir, sering terjadi masalah terkait dana.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Amal No. 23, Bukit Agung, 62125, Pati, Jawa Tengah, Indonesia',
                'created_at' => Carbon::now()->subYears(1)->subMonths(6),
                'updated_at' => Carbon::now()->subMonths(3),
            ],
            [
                'code' => 'AD012',
                'category_event' => 'kesehatan',
                'content' => 'Puskesmas setempat sering kehabisan stok obat-obatan dasar.',
                'media' => NULL,
                'status' => 'sudah_diverifikasi',
                'address' => 'Jl. Kesehatan No. 45, Rumbai, 28157, Pekanbaru, Riau, Indonesia',
                'created_at' => Carbon::now()->subYears(2)->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(1),
            ],
            [
                'code' => 'AD013',
                'category_event' => 'ketertiban_umum',
                'content' => 'Setiap malam kendaraan diparkir sembarangan di depan rumah saya, mengganggu akses jalan.',
                'media' => NULL,
                'status' => 'sudah_selesai',
                'address' => 'Jl. Perdamaian No. 17, Muncar, 68472, Banyuwangi, Jawa Timur, Indonesia',
                'created_at' => Carbon::now()->subYears(1)->subMonths(9),
                'updated_at' => Carbon::now()->subMonths(2),
            ],
            [
                'code' => 'AD014',
                'category_event' => 'pekerjaan_umum_dan_penataan_ruang',
                'content' => 'Proyek drainase di desa kami tidak selesai tepat waktu, jalan menjadi rusak parah.',
                'media' => NULL,
                'status' => 'ditolak',
                'address' => 'Jl. Pembangunan No. 5, Ampelgading, 65182, Malang, Jawa Timur, Indonesia',
                'created_at' => Carbon::now()->subMonths(10),
                'updated_at' => Carbon::now()->subMonths(6),
            ],
            [
                'code' => 'AD015',
                'category_event' => 'pemberantasan_penyalahgunaan',
                'content' => 'Ada aktivitas mencurigakan terkait narkoba di lingkungan sekitar RT 03.',
                'media' => NULL,
                'status' => 'sudah_selesai',
                'address' => 'Jl. Kesatria No. 7, Pondok Gede, 17411, Kota Bekasi, Jawa Barat, Indonesia',
                'created_at' => Carbon::now()->subYears(1),
                'updated_at' => Carbon::now()->subMonths(7),
            ],
            [
                'code' => 'AD016',
                'category_event' => 'peredaran_gelap_narkotika',
                'content' => 'Sering ada laporan peredaran narkoba di desa kami, tetapi belum ada tindakan tegas.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Mawar No. 12, Sekip, 43221, Purwakarta, Jawa Barat, Indonesia',
                'created_at' => Carbon::now()->subMonths(7),
                'updated_at' => Carbon::now()->subMonths(4),
            ],
            [
                'code' => 'AD017',
                'category_event' => 'politik_dan_hukum',
                'content' => 'Ada kegiatan kampanye politik di area yang seharusnya netral seperti sekolah.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Hukum No. 99, Sidorejo, 29216, Pangkal Pinang, Kepulauan Bangka Belitung, Indonesia',
                'created_at' => Carbon::now()->subYears(2),
                'updated_at' => Carbon::now()->subMonths(8),
            ],
            [
                'code' => 'AD018',
                'category_event' => 'peniadaan_mudik',
                'content' => 'Penerapan aturan mudik di desa saya tidak dipantau dengan baik, banyak warga yang melanggar.',
                'media' => NULL,
                'status' => 'sudah_diverifikasi',
                'address' => 'Jl. Maju Terus No. 88, Trenggalek, 66371, Jawa Timur, Indonesia',
                'created_at' => Carbon::now()->subYears(3),
                'updated_at' => Carbon::now()->subMonths(10),
            ],
            [
                'code' => 'AD019',
                'category_event' => 'perlindungan_konsumen',
                'content' => 'Produk elektronik yang saya beli dari toko ternyata cacat dan tidak bisa ditukar.',
                'media' => NULL,
                'status' => 'ditolak',
                'address' => 'Jl. Konsumen No. 20, Banjarbaru, 70712, Kalimantan Selatan, Indonesia',
                'created_at' => Carbon::now()->subYears(1)->subMonths(2),
                'updated_at' => Carbon::now()->subMonths(4),
            ],
            [
                'code' => 'AD020',
                'category_event' => 'topik_lainnya',
                'content' => 'Prosedur pelayanan di kantor pemerintah sangat lambat dan tidak ramah terhadap warga.',
                'media' => NULL,
                'status' => 'belum_diverifikasi',
                'address' => 'Jl. Kenari No. 55, Karanganyar, 57731, Solo, Jawa Tengah, Indonesia',
                'created_at' => Carbon::now()->subYears(1),
                'updated_at' => Carbon::now()->subMonths(5),
            ]
        ]);
    }
}
